sudo: required

language: python

services:
  - docker

before_install:
  - docker pull acostapazo/bob.gradiant.face.databases:latest

script:
  - docker run -v $(pwd):/bob.gradiant.face.database acostapazo/bob.gradiant.face.databases:latest bin/bash -c "source activate bob.gradiant; cd bob.gradiant.face.database; ./ci.sh"

# Deploy using travis builtin GitHub Pages support
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc/html
  github_token: $GITHUB_TOKEN
  on:
    branch: master
